nelmio_api_doc_v1:
    path: /v1
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger
        area: v1

nelmio_api_doc_v2:
    path: /v2
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger
        area: v2

app.swagger_ui:
    path: /
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
