# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener:  force
    allowed_methods_listener:  true
    routing_loader: false
    serializer:
        serialize_null: true
    view:
        view_response_listener:  true
        formats:
            json: true
            yaml: false
            xml: false
        mime_types:
            json: [ 'application/json', 'application/x-json' ]
            yaml: [ 'text/yaml', 'application/x-yaml' ]

#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        enabled: true
        rules:
            - { path: ^/jacq-services/,  methods: [GET], prefer_extension: true, fallback_format: json, priorities: [json] }
#            - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true } #https://github.com/FriendsOfSymfony/FOSRestBundle/issues/650#issuecomment-31449035
