nelmio_api_doc:
    documentation:
        info:
            title: JACQ API Services documentation
            description: distributed herbarium collection system
            version: 1.0.0
    areas:
        default:
            disable_default_routes: true
        v1:
            path_patterns: [ ^/v1/ ]
        v2:
            path_patterns: [ ^/v2/ ]

